// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ingest_query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 转账事件查询类型，表示查询方向
type TransferQueryType int32

const (
	TransferQueryType_ALL         TransferQueryType = 0 // 查询所有转账事件，from_wallet 或 to_wallet 任意匹配
	TransferQueryType_FROM_WALLET TransferQueryType = 1 // 仅查询 from_wallet 等于 user_wallet 的事件
	TransferQueryType_TO_WALLET   TransferQueryType = 2 // 仅查询 to_wallet 等于 user_wallet 的事件
)

// Enum value maps for TransferQueryType.
var (
	TransferQueryType_name = map[int32]string{
		0: "ALL",
		1: "FROM_WALLET",
		2: "TO_WALLET",
	}
	TransferQueryType_value = map[string]int32{
		"ALL":         0,
		"FROM_WALLET": 1,
		"TO_WALLET":   2,
	}
)

func (x TransferQueryType) Enum() *TransferQueryType {
	p := new(TransferQueryType)
	*p = x
	return p
}

func (x TransferQueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferQueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_ingest_query_proto_enumTypes[0].Descriptor()
}

func (TransferQueryType) Type() protoreflect.EnumType {
	return &file_ingest_query_proto_enumTypes[0]
}

func (x TransferQueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferQueryType.Descriptor instead.
func (TransferQueryType) EnumDescriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{0}
}

type EventIDsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventIds      []uint64               `protobuf:"varint,1,rep,packed,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"` // 事件ID列表，批量查询用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventIDsReq) Reset() {
	*x = EventIDsReq{}
	mi := &file_ingest_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIDsReq) ProtoMessage() {}

func (x *EventIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIDsReq.ProtoReflect.Descriptor instead.
func (*EventIDsReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{0}
}

func (x *EventIDsReq) GetEventIds() []uint64 {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type ChainEventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Event         *ChainEvent            `protobuf:"bytes,2,opt,name=event,proto3,oneof" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainEventResult) Reset() {
	*x = ChainEventResult{}
	mi := &file_ingest_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainEventResult) ProtoMessage() {}

func (x *ChainEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainEventResult.ProtoReflect.Descriptor instead.
func (*ChainEventResult) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{1}
}

func (x *ChainEventResult) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ChainEventResult) GetEvent() *ChainEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ChainEventResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResp) Reset() {
	*x = EventListResp{}
	mi := &file_ingest_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResp) ProtoMessage() {}

func (x *EventListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResp.ProtoReflect.Descriptor instead.
func (*EventListResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{2}
}

func (x *EventListResp) GetResults() []*ChainEventResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UserEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserWallet    string                 `protobuf:"bytes,1,opt,name=user_wallet,json=userWallet,proto3" json:"user_wallet,omitempty"`      // 用户地址，查询与该地址相关的事件
	EventType     []uint32               `protobuf:"varint,2,rep,packed,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型过滤，可多选，不传则查询全部
	EventId       *uint64                `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`        // 分页游标，查询 event_id 之前的数据（不含）
	Limit         *uint32                `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                           // 限制返回条数，建议默认10-20，最大1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEventReq) Reset() {
	*x = UserEventReq{}
	mi := &file_ingest_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEventReq) ProtoMessage() {}

func (x *UserEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEventReq.ProtoReflect.Descriptor instead.
func (*UserEventReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{3}
}

func (x *UserEventReq) GetUserWallet() string {
	if x != nil {
		return x.UserWallet
	}
	return ""
}

func (x *UserEventReq) GetEventType() []uint32 {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *UserEventReq) GetEventId() uint64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *UserEventReq) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type PoolEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolAddress   string                 `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`   // 池子地址
	EventType     []uint32               `protobuf:"varint,2,rep,packed,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型过滤
	EventId       *uint64                `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`        // 分页游标
	Limit         *uint32                `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                           // 限制返回条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolEventReq) Reset() {
	*x = PoolEventReq{}
	mi := &file_ingest_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolEventReq) ProtoMessage() {}

func (x *PoolEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolEventReq.ProtoReflect.Descriptor instead.
func (*PoolEventReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{4}
}

func (x *PoolEventReq) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *PoolEventReq) GetEventType() []uint32 {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *PoolEventReq) GetEventId() uint64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *PoolEventReq) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ChainEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventIdHash   uint32                 `protobuf:"varint,1,opt,name=event_id_hash,json=eventIdHash,proto3" json:"event_id_hash,omitempty"`
	EventId       uint64                 `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     uint32                 `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Dex           uint32                 `protobuf:"varint,4,opt,name=dex,proto3" json:"dex,omitempty"`
	UserWallet    string                 `protobuf:"bytes,5,opt,name=user_wallet,json=userWallet,proto3" json:"user_wallet,omitempty"` // 交易发起者地址，等同于 from_wallet
	ToWallet      string                 `protobuf:"bytes,6,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`       // 交易接收者地址
	PoolAddress   string                 `protobuf:"bytes,7,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	Token         string                 `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	QuoteToken    string                 `protobuf:"bytes,9,opt,name=quote_token,json=quoteToken,proto3" json:"quote_token,omitempty"`
	TokenAmount   uint64                 `protobuf:"varint,10,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	QuoteAmount   uint64                 `protobuf:"varint,11,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	VolumeUsd     float64                `protobuf:"fixed64,12,opt,name=volume_usd,json=volumeUsd,proto3" json:"volume_usd,omitempty"` // 估算的美元交易量
	PriceUsd      float64                `protobuf:"fixed64,13,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`    // 估算的美元价格
	TxHash        string                 `protobuf:"bytes,14,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Signer        string                 `protobuf:"bytes,15,opt,name=signer,proto3" json:"signer,omitempty"`
	BlockTime     uint32                 `protobuf:"varint,16,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	CreateAt      uint32                 `protobuf:"varint,17,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainEvent) Reset() {
	*x = ChainEvent{}
	mi := &file_ingest_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainEvent) ProtoMessage() {}

func (x *ChainEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainEvent.ProtoReflect.Descriptor instead.
func (*ChainEvent) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{5}
}

func (x *ChainEvent) GetEventIdHash() uint32 {
	if x != nil {
		return x.EventIdHash
	}
	return 0
}

func (x *ChainEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ChainEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *ChainEvent) GetDex() uint32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *ChainEvent) GetUserWallet() string {
	if x != nil {
		return x.UserWallet
	}
	return ""
}

func (x *ChainEvent) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *ChainEvent) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *ChainEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChainEvent) GetQuoteToken() string {
	if x != nil {
		return x.QuoteToken
	}
	return ""
}

func (x *ChainEvent) GetTokenAmount() uint64 {
	if x != nil {
		return x.TokenAmount
	}
	return 0
}

func (x *ChainEvent) GetQuoteAmount() uint64 {
	if x != nil {
		return x.QuoteAmount
	}
	return 0
}

func (x *ChainEvent) GetVolumeUsd() float64 {
	if x != nil {
		return x.VolumeUsd
	}
	return 0
}

func (x *ChainEvent) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *ChainEvent) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ChainEvent) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *ChainEvent) GetBlockTime() uint32 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *ChainEvent) GetCreateAt() uint32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

type EventResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ChainEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResp) Reset() {
	*x = EventResp{}
	mi := &file_ingest_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResp) ProtoMessage() {}

func (x *EventResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResp.ProtoReflect.Descriptor instead.
func (*EventResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{6}
}

func (x *EventResp) GetEvents() []*ChainEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TransferEventQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserWallet    string                 `protobuf:"bytes,1,opt,name=user_wallet,json=userWallet,proto3" json:"user_wallet,omitempty"`                         // 要查询的用户地址
	QueryType     TransferQueryType      `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3,enum=pb.TransferQueryType" json:"query_type,omitempty"` // 查询类型：from_wallet / to_wallet / all
	EventId       *uint64                `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`                           // 分页游标，查询 event_id 之前的数据
	Limit         *uint32                `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                                              // 返回条数限制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferEventQueryReq) Reset() {
	*x = TransferEventQueryReq{}
	mi := &file_ingest_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEventQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEventQueryReq) ProtoMessage() {}

func (x *TransferEventQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEventQueryReq.ProtoReflect.Descriptor instead.
func (*TransferEventQueryReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{7}
}

func (x *TransferEventQueryReq) GetUserWallet() string {
	if x != nil {
		return x.UserWallet
	}
	return ""
}

func (x *TransferEventQueryReq) GetQueryType() TransferQueryType {
	if x != nil {
		return x.QueryType
	}
	return TransferQueryType_ALL
}

func (x *TransferEventQueryReq) GetEventId() uint64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *TransferEventQueryReq) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type TokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReq) Reset() {
	*x = TokenReq{}
	mi := &file_ingest_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReq) ProtoMessage() {}

func (x *TokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReq.ProtoReflect.Descriptor instead.
func (*TokenReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{8}
}

func (x *TokenReq) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type TokenTopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Limit         *uint32                `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"` // 可选参数，查询的最多账户数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTopReq) Reset() {
	*x = TokenTopReq{}
	mi := &file_ingest_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTopReq) ProtoMessage() {}

func (x *TokenTopReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTopReq.ProtoReflect.Descriptor instead.
func (*TokenTopReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{9}
}

func (x *TokenTopReq) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenTopReq) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type OwnerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	TokenAddress  *string                `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3,oneof" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerReq) Reset() {
	*x = OwnerReq{}
	mi := &file_ingest_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerReq) ProtoMessage() {}

func (x *OwnerReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerReq.ProtoReflect.Descriptor instead.
func (*OwnerReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{10}
}

func (x *OwnerReq) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *OwnerReq) GetTokenAddress() string {
	if x != nil && x.TokenAddress != nil {
		return *x.TokenAddress
	}
	return ""
}

type AccountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsReq) Reset() {
	*x = AccountsReq{}
	mi := &file_ingest_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsReq) ProtoMessage() {}

func (x *AccountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsReq.ProtoReflect.Descriptor instead.
func (*AccountsReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{11}
}

func (x *AccountsReq) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Balance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress string                 `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	OwnerAddress   string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	TokenAddress   string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Balance        uint64                 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	LastEventId    uint64                 `protobuf:"varint,5,opt,name=last_event_id,json=lastEventId,proto3" json:"last_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_ingest_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{12}
}

func (x *Balance) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *Balance) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *Balance) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Balance) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Balance) GetLastEventId() uint64 {
	if x != nil {
		return x.LastEventId
	}
	return 0
}

type BalanceResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress string                 `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Balance        *Balance               `protobuf:"bytes,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResult) Reset() {
	*x = BalanceResult{}
	mi := &file_ingest_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResult) ProtoMessage() {}

func (x *BalanceResult) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResult.ProtoReflect.Descriptor instead.
func (*BalanceResult) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{13}
}

func (x *BalanceResult) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *BalanceResult) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type BalanceListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BalanceResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceListResp) Reset() {
	*x = BalanceListResp{}
	mi := &file_ingest_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceListResp) ProtoMessage() {}

func (x *BalanceListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceListResp.ProtoReflect.Descriptor instead.
func (*BalanceListResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{14}
}

func (x *BalanceListResp) GetResults() []*BalanceResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResp) Reset() {
	*x = BalanceResp{}
	mi := &file_ingest_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResp) ProtoMessage() {}

func (x *BalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResp.ProtoReflect.Descriptor instead.
func (*BalanceResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{15}
}

func (x *BalanceResp) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type Holder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holder) Reset() {
	*x = Holder{}
	mi := &file_ingest_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holder) ProtoMessage() {}

func (x *Holder) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holder.ProtoReflect.Descriptor instead.
func (*Holder) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{16}
}

func (x *Holder) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *Holder) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type HolderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holders       []*Holder              `protobuf:"bytes,1,rep,name=holders,proto3" json:"holders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderListResp) Reset() {
	*x = HolderListResp{}
	mi := &file_ingest_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderListResp) ProtoMessage() {}

func (x *HolderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderListResp.ProtoReflect.Descriptor instead.
func (*HolderListResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{17}
}

func (x *HolderListResp) GetHolders() []*Holder {
	if x != nil {
		return x.Holders
	}
	return nil
}

type HolderCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderCountResp) Reset() {
	*x = HolderCountResp{}
	mi := &file_ingest_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderCountResp) ProtoMessage() {}

func (x *HolderCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderCountResp.ProtoReflect.Descriptor instead.
func (*HolderCountResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{18}
}

func (x *HolderCountResp) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PoolAddressesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolAddresses []string               `protobuf:"bytes,1,rep,name=pool_addresses,json=poolAddresses,proto3" json:"pool_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAddressesReq) Reset() {
	*x = PoolAddressesReq{}
	mi := &file_ingest_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAddressesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAddressesReq) ProtoMessage() {}

func (x *PoolAddressesReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAddressesReq.ProtoReflect.Descriptor instead.
func (*PoolAddressesReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{19}
}

func (x *PoolAddressesReq) GetPoolAddresses() []string {
	if x != nil {
		return x.PoolAddresses
	}
	return nil
}

type PoolTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseToken     string                 `protobuf:"bytes,1,opt,name=base_token,json=baseToken,proto3" json:"base_token,omitempty"`
	QuoteToken    *string                `protobuf:"bytes,2,opt,name=quote_token,json=quoteToken,proto3,oneof" json:"quote_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolTokenReq) Reset() {
	*x = PoolTokenReq{}
	mi := &file_ingest_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolTokenReq) ProtoMessage() {}

func (x *PoolTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolTokenReq.ProtoReflect.Descriptor instead.
func (*PoolTokenReq) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{20}
}

func (x *PoolTokenReq) GetBaseToken() string {
	if x != nil {
		return x.BaseToken
	}
	return ""
}

func (x *PoolTokenReq) GetQuoteToken() string {
	if x != nil && x.QuoteToken != nil {
		return *x.QuoteToken
	}
	return ""
}

type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolAddress   string                 `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	Dex           uint32                 `protobuf:"varint,2,opt,name=dex,proto3" json:"dex,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	QuoteAddress  string                 `protobuf:"bytes,4,opt,name=quote_address,json=quoteAddress,proto3" json:"quote_address,omitempty"`
	TokenAccount  string                 `protobuf:"bytes,5,opt,name=token_account,json=tokenAccount,proto3" json:"token_account,omitempty"`
	QuoteAccount  string                 `protobuf:"bytes,6,opt,name=quote_account,json=quoteAccount,proto3" json:"quote_account,omitempty"`
	CreateAt      uint32                 `protobuf:"varint,7,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      uint32                 `protobuf:"varint,8,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_ingest_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{21}
}

func (x *Pool) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *Pool) GetDex() uint32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *Pool) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Pool) GetQuoteAddress() string {
	if x != nil {
		return x.QuoteAddress
	}
	return ""
}

func (x *Pool) GetTokenAccount() string {
	if x != nil {
		return x.TokenAccount
	}
	return ""
}

func (x *Pool) GetQuoteAccount() string {
	if x != nil {
		return x.QuoteAccount
	}
	return ""
}

func (x *Pool) GetCreateAt() uint32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Pool) GetUpdateAt() uint32 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type PoolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolAddress   string                 `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	Pools         []*Pool                `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolResult) Reset() {
	*x = PoolResult{}
	mi := &file_ingest_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolResult) ProtoMessage() {}

func (x *PoolResult) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolResult.ProtoReflect.Descriptor instead.
func (*PoolResult) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{22}
}

func (x *PoolResult) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *PoolResult) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

type PoolListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PoolResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolListResp) Reset() {
	*x = PoolListResp{}
	mi := &file_ingest_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolListResp) ProtoMessage() {}

func (x *PoolListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolListResp.ProtoReflect.Descriptor instead.
func (*PoolListResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{23}
}

func (x *PoolListResp) GetResults() []*PoolResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type PoolResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*Pool                `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolResp) Reset() {
	*x = PoolResp{}
	mi := &file_ingest_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolResp) ProtoMessage() {}

func (x *PoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_ingest_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolResp.ProtoReflect.Descriptor instead.
func (*PoolResp) Descriptor() ([]byte, []int) {
	return file_ingest_query_proto_rawDescGZIP(), []int{24}
}

func (x *PoolResp) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

var File_ingest_query_proto protoreflect.FileDescriptor

const file_ingest_query_proto_rawDesc = "" +
	"\n" +
	"\x12ingest_query.proto\x12\x02pb\"*\n" +
	"\vEventIDsReq\x12\x1b\n" +
	"\tevent_ids\x18\x01 \x03(\x04R\beventIds\"b\n" +
	"\x10ChainEventResult\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12)\n" +
	"\x05event\x18\x02 \x01(\v2\x0e.pb.ChainEventH\x00R\x05event\x88\x01\x01B\b\n" +
	"\x06_event\"?\n" +
	"\rEventListResp\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.pb.ChainEventResultR\aresults\"\xa0\x01\n" +
	"\fUserEventReq\x12\x1f\n" +
	"\vuser_wallet\x18\x01 \x01(\tR\n" +
	"userWallet\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x03(\rR\teventType\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\x04H\x00R\aeventId\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x01R\x05limit\x88\x01\x01B\v\n" +
	"\t_event_idB\b\n" +
	"\x06_limit\"\xa2\x01\n" +
	"\fPoolEventReq\x12!\n" +
	"\fpool_address\x18\x01 \x01(\tR\vpoolAddress\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x03(\rR\teventType\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\x04H\x00R\aeventId\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x01R\x05limit\x88\x01\x01B\v\n" +
	"\t_event_idB\b\n" +
	"\x06_limit\"\x83\x04\n" +
	"\n" +
	"ChainEvent\x12\"\n" +
	"\revent_id_hash\x18\x01 \x01(\rR\veventIdHash\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x04R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\rR\teventType\x12\x10\n" +
	"\x03dex\x18\x04 \x01(\rR\x03dex\x12\x1f\n" +
	"\vuser_wallet\x18\x05 \x01(\tR\n" +
	"userWallet\x12\x1b\n" +
	"\tto_wallet\x18\x06 \x01(\tR\btoWallet\x12!\n" +
	"\fpool_address\x18\a \x01(\tR\vpoolAddress\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\x12\x1f\n" +
	"\vquote_token\x18\t \x01(\tR\n" +
	"quoteToken\x12!\n" +
	"\ftoken_amount\x18\n" +
	" \x01(\x04R\vtokenAmount\x12!\n" +
	"\fquote_amount\x18\v \x01(\x04R\vquoteAmount\x12\x1d\n" +
	"\n" +
	"volume_usd\x18\f \x01(\x01R\tvolumeUsd\x12\x1b\n" +
	"\tprice_usd\x18\r \x01(\x01R\bpriceUsd\x12\x17\n" +
	"\atx_hash\x18\x0e \x01(\tR\x06txHash\x12\x16\n" +
	"\x06signer\x18\x0f \x01(\tR\x06signer\x12\x1d\n" +
	"\n" +
	"block_time\x18\x10 \x01(\rR\tblockTime\x12\x1b\n" +
	"\tcreate_at\x18\x11 \x01(\rR\bcreateAt\"3\n" +
	"\tEventResp\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.pb.ChainEventR\x06events\"\xc0\x01\n" +
	"\x15TransferEventQueryReq\x12\x1f\n" +
	"\vuser_wallet\x18\x01 \x01(\tR\n" +
	"userWallet\x124\n" +
	"\n" +
	"query_type\x18\x02 \x01(\x0e2\x15.pb.TransferQueryTypeR\tqueryType\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\x04H\x00R\aeventId\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\rH\x01R\x05limit\x88\x01\x01B\v\n" +
	"\t_event_idB\b\n" +
	"\x06_limit\"/\n" +
	"\bTokenReq\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\"W\n" +
	"\vTokenTopReq\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"k\n" +
	"\bOwnerReq\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12(\n" +
	"\rtoken_address\x18\x02 \x01(\tH\x00R\ftokenAddress\x88\x01\x01B\x10\n" +
	"\x0e_token_address\")\n" +
	"\vAccountsReq\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\"\xba\x01\n" +
	"\aBalance\x12'\n" +
	"\x0faccount_address\x18\x01 \x01(\tR\x0eaccountAddress\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x04R\abalance\x12\"\n" +
	"\rlast_event_id\x18\x05 \x01(\x04R\vlastEventId\"p\n" +
	"\rBalanceResult\x12'\n" +
	"\x0faccount_address\x18\x01 \x01(\tR\x0eaccountAddress\x12*\n" +
	"\abalance\x18\x02 \x01(\v2\v.pb.BalanceH\x00R\abalance\x88\x01\x01B\n" +
	"\n" +
	"\b_balance\">\n" +
	"\x0fBalanceListResp\x12+\n" +
	"\aresults\x18\x01 \x03(\v2\x11.pb.BalanceResultR\aresults\"6\n" +
	"\vBalanceResp\x12'\n" +
	"\bbalances\x18\x01 \x03(\v2\v.pb.BalanceR\bbalances\"G\n" +
	"\x06Holder\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\"6\n" +
	"\x0eHolderListResp\x12$\n" +
	"\aholders\x18\x01 \x03(\v2\n" +
	".pb.HolderR\aholders\"'\n" +
	"\x0fHolderCountResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"9\n" +
	"\x10PoolAddressesReq\x12%\n" +
	"\x0epool_addresses\x18\x01 \x03(\tR\rpoolAddresses\"c\n" +
	"\fPoolTokenReq\x12\x1d\n" +
	"\n" +
	"base_token\x18\x01 \x01(\tR\tbaseToken\x12$\n" +
	"\vquote_token\x18\x02 \x01(\tH\x00R\n" +
	"quoteToken\x88\x01\x01B\x0e\n" +
	"\f_quote_token\"\x89\x02\n" +
	"\x04Pool\x12!\n" +
	"\fpool_address\x18\x01 \x01(\tR\vpoolAddress\x12\x10\n" +
	"\x03dex\x18\x02 \x01(\rR\x03dex\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12#\n" +
	"\rquote_address\x18\x04 \x01(\tR\fquoteAddress\x12#\n" +
	"\rtoken_account\x18\x05 \x01(\tR\ftokenAccount\x12#\n" +
	"\rquote_account\x18\x06 \x01(\tR\fquoteAccount\x12\x1b\n" +
	"\tcreate_at\x18\a \x01(\rR\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\b \x01(\rR\bupdateAt\"O\n" +
	"\n" +
	"PoolResult\x12!\n" +
	"\fpool_address\x18\x01 \x01(\tR\vpoolAddress\x12\x1e\n" +
	"\x05pools\x18\x02 \x03(\v2\b.pb.PoolR\x05pools\"8\n" +
	"\fPoolListResp\x12(\n" +
	"\aresults\x18\x01 \x03(\v2\x0e.pb.PoolResultR\aresults\"*\n" +
	"\bPoolResp\x12\x1e\n" +
	"\x05pools\x18\x01 \x03(\v2\b.pb.PoolR\x05pools*<\n" +
	"\x11TransferQueryType\x12\a\n" +
	"\x03ALL\x10\x00\x12\x0f\n" +
	"\vFROM_WALLET\x10\x01\x12\r\n" +
	"\tTO_WALLET\x10\x022\xe4\x04\n" +
	"\x12IngestQueryService\x126\n" +
	"\x10QueryEventsByIDs\x12\x0f.pb.EventIDsReq\x1a\x11.pb.EventListResp\x124\n" +
	"\x11QueryEventsByUser\x12\x10.pb.UserEventReq\x1a\r.pb.EventResp\x124\n" +
	"\x11QueryEventsByPool\x12\x10.pb.PoolEventReq\x1a\r.pb.EventResp\x12?\n" +
	"\x13QueryTransferEvents\x12\x19.pb.TransferEventQueryReq\x1a\r.pb.EventResp\x12=\n" +
	"\x16QueryTopHoldersByToken\x12\x0f.pb.TokenTopReq\x1a\x12.pb.HolderListResp\x12<\n" +
	"\x17QueryHolderCountByToken\x12\f.pb.TokenReq\x1a\x13.pb.HolderCountResp\x125\n" +
	"\x14QueryBalancesByOwner\x12\f.pb.OwnerReq\x1a\x0f.pb.BalanceResp\x12?\n" +
	"\x17QueryBalancesByAccounts\x12\x0f.pb.AccountsReq\x1a\x13.pb.BalanceListResp\x12?\n" +
	"\x15QueryPoolsByAddresses\x12\x14.pb.PoolAddressesReq\x1a\x10.pb.PoolListResp\x123\n" +
	"\x11QueryPoolsByToken\x12\x10.pb.PoolTokenReq\x1a\f.pb.PoolRespB\x16Z\x14dex-ingest-sol/pb;pbb\x06proto3"

var (
	file_ingest_query_proto_rawDescOnce sync.Once
	file_ingest_query_proto_rawDescData []byte
)

func file_ingest_query_proto_rawDescGZIP() []byte {
	file_ingest_query_proto_rawDescOnce.Do(func() {
		file_ingest_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingest_query_proto_rawDesc), len(file_ingest_query_proto_rawDesc)))
	})
	return file_ingest_query_proto_rawDescData
}

var file_ingest_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ingest_query_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_ingest_query_proto_goTypes = []any{
	(TransferQueryType)(0),        // 0: pb.TransferQueryType
	(*EventIDsReq)(nil),           // 1: pb.EventIDsReq
	(*ChainEventResult)(nil),      // 2: pb.ChainEventResult
	(*EventListResp)(nil),         // 3: pb.EventListResp
	(*UserEventReq)(nil),          // 4: pb.UserEventReq
	(*PoolEventReq)(nil),          // 5: pb.PoolEventReq
	(*ChainEvent)(nil),            // 6: pb.ChainEvent
	(*EventResp)(nil),             // 7: pb.EventResp
	(*TransferEventQueryReq)(nil), // 8: pb.TransferEventQueryReq
	(*TokenReq)(nil),              // 9: pb.TokenReq
	(*TokenTopReq)(nil),           // 10: pb.TokenTopReq
	(*OwnerReq)(nil),              // 11: pb.OwnerReq
	(*AccountsReq)(nil),           // 12: pb.AccountsReq
	(*Balance)(nil),               // 13: pb.Balance
	(*BalanceResult)(nil),         // 14: pb.BalanceResult
	(*BalanceListResp)(nil),       // 15: pb.BalanceListResp
	(*BalanceResp)(nil),           // 16: pb.BalanceResp
	(*Holder)(nil),                // 17: pb.Holder
	(*HolderListResp)(nil),        // 18: pb.HolderListResp
	(*HolderCountResp)(nil),       // 19: pb.HolderCountResp
	(*PoolAddressesReq)(nil),      // 20: pb.PoolAddressesReq
	(*PoolTokenReq)(nil),          // 21: pb.PoolTokenReq
	(*Pool)(nil),                  // 22: pb.Pool
	(*PoolResult)(nil),            // 23: pb.PoolResult
	(*PoolListResp)(nil),          // 24: pb.PoolListResp
	(*PoolResp)(nil),              // 25: pb.PoolResp
}
var file_ingest_query_proto_depIdxs = []int32{
	6,  // 0: pb.ChainEventResult.event:type_name -> pb.ChainEvent
	2,  // 1: pb.EventListResp.results:type_name -> pb.ChainEventResult
	6,  // 2: pb.EventResp.events:type_name -> pb.ChainEvent
	0,  // 3: pb.TransferEventQueryReq.query_type:type_name -> pb.TransferQueryType
	13, // 4: pb.BalanceResult.balance:type_name -> pb.Balance
	14, // 5: pb.BalanceListResp.results:type_name -> pb.BalanceResult
	13, // 6: pb.BalanceResp.balances:type_name -> pb.Balance
	17, // 7: pb.HolderListResp.holders:type_name -> pb.Holder
	22, // 8: pb.PoolResult.pools:type_name -> pb.Pool
	23, // 9: pb.PoolListResp.results:type_name -> pb.PoolResult
	22, // 10: pb.PoolResp.pools:type_name -> pb.Pool
	1,  // 11: pb.IngestQueryService.QueryEventsByIDs:input_type -> pb.EventIDsReq
	4,  // 12: pb.IngestQueryService.QueryEventsByUser:input_type -> pb.UserEventReq
	5,  // 13: pb.IngestQueryService.QueryEventsByPool:input_type -> pb.PoolEventReq
	8,  // 14: pb.IngestQueryService.QueryTransferEvents:input_type -> pb.TransferEventQueryReq
	10, // 15: pb.IngestQueryService.QueryTopHoldersByToken:input_type -> pb.TokenTopReq
	9,  // 16: pb.IngestQueryService.QueryHolderCountByToken:input_type -> pb.TokenReq
	11, // 17: pb.IngestQueryService.QueryBalancesByOwner:input_type -> pb.OwnerReq
	12, // 18: pb.IngestQueryService.QueryBalancesByAccounts:input_type -> pb.AccountsReq
	20, // 19: pb.IngestQueryService.QueryPoolsByAddresses:input_type -> pb.PoolAddressesReq
	21, // 20: pb.IngestQueryService.QueryPoolsByToken:input_type -> pb.PoolTokenReq
	3,  // 21: pb.IngestQueryService.QueryEventsByIDs:output_type -> pb.EventListResp
	7,  // 22: pb.IngestQueryService.QueryEventsByUser:output_type -> pb.EventResp
	7,  // 23: pb.IngestQueryService.QueryEventsByPool:output_type -> pb.EventResp
	7,  // 24: pb.IngestQueryService.QueryTransferEvents:output_type -> pb.EventResp
	18, // 25: pb.IngestQueryService.QueryTopHoldersByToken:output_type -> pb.HolderListResp
	19, // 26: pb.IngestQueryService.QueryHolderCountByToken:output_type -> pb.HolderCountResp
	16, // 27: pb.IngestQueryService.QueryBalancesByOwner:output_type -> pb.BalanceResp
	15, // 28: pb.IngestQueryService.QueryBalancesByAccounts:output_type -> pb.BalanceListResp
	24, // 29: pb.IngestQueryService.QueryPoolsByAddresses:output_type -> pb.PoolListResp
	25, // 30: pb.IngestQueryService.QueryPoolsByToken:output_type -> pb.PoolResp
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ingest_query_proto_init() }
func file_ingest_query_proto_init() {
	if File_ingest_query_proto != nil {
		return
	}
	file_ingest_query_proto_msgTypes[1].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[3].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[4].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[7].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[9].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[10].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[13].OneofWrappers = []any{}
	file_ingest_query_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingest_query_proto_rawDesc), len(file_ingest_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingest_query_proto_goTypes,
		DependencyIndexes: file_ingest_query_proto_depIdxs,
		EnumInfos:         file_ingest_query_proto_enumTypes,
		MessageInfos:      file_ingest_query_proto_msgTypes,
	}.Build()
	File_ingest_query_proto = out.File
	file_ingest_query_proto_goTypes = nil
	file_ingest_query_proto_depIdxs = nil
}
